name: CI
on: [push, pull_request]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: rm -rf node_modules
    - uses: actions/upload-artifact@v2
      with:
        name: frontend-output
        path: .
  build-website:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'refinedmods/sitegen'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: go build
    - uses: actions/download-artifact@v2
      with:
        name: frontend-output
    - run: chown $USER sitegen
    - run: sudo ./sitegen build
      env:
        SITEGEN_GITHUB_TOKEN: ${{ secrets.SITEGEN_GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build-website
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: output
        path: output/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: output/
